motors:
  - motor_id: 1
    joint_name: 'right_hip_pitch'
    motor_type: 'A1'
    output_kp: 30.0
    output_kd: 0.5
    movement_speed: 300
  - motor_id: 2
    joint_name: 'right_knee'
    motor_type: 'A1'
    output_kp: 30.0
    output_kd: 0.5
    movement_speed: 250
motor_limits:
  1:
    min_position: -69.9456482
    max_position: 131.242264
  2:
    min_position: -50.2402306
    max_position: 130.027725
